### ISSUE TITLE
Discuss Idea

### ISSUE THREAD

**Issue by jeonghyeonee** [jeonghyeonee/Memoriary#1]

**Comment by siheon0411** [comment]
## 치매예방 앱

<컨셉>
노인들의 치매예방을 위한 일상 종합 어플리케이션
<주요기능>
    - 일상적으로 있었던 일(일기와 같은형식)으로 저장
    - 해야할 일(to-do list)도 저장
    - 분석
    - 퀴즈로 제시 → 맞추면 좋음 (의학적 실험 결과 뒷받침)
<기능구현>
    - 로그인/로그아웃
    - 음성인식을 통한 일기 작성 (TTS, STT)
    - 음성인식을 통한 to-do list 작성
    - DB 여러개
    - 수업때 배운 기능들 여러개
    - VR/AR
    - 카카오맵 API
    - Karlo
    - 첨삭 API
    - 알림/알람

**Comment by jeonghyeonee** [comment]
AR Function
AR로 앞에서 운동 해주는 거?
포켓몬고 같은....? 알짱알짱...
Limit: 기계?

못하는 걸까요...?

**Comment by jeonghyeonee** [comment]
퀴즈를 내는 기능은 GPT API를 활용하여 간단한 문제를 출제하게 하는 것은?

e.g. <일기 내용> + 간단한 퀴즈 만들어줘 -> 다지선다 문항 출제 가능

**Comment by siheon0411** [comment]
https://chat.openai.com/share/52aa02a0-2498-48aa-9f5c-52747ff299c2
퀴즈출제 예시

**Comment by jeonghyeonee** [comment]
**push notification**: 성공하면 ^_^, 망하면 ....다 망가질 수 있음
그림일기: API 결과라서 딱히 개발 입장에서는 좋지 않을 수 있음
**Image Detection**: API call vs. 자체적 개발 
Shaking, **Sensor 이용**
음성인식
API Call로 하면 의미가 퇴색됨

**Comment by jeonghyeonee** [comment]
피드백:
1. Karlo 영어 지원하는지
2. MySQL은 뭐에다 쓸건지, 서버 다 구축하는건지
3. 박수는 어떻게 인식하는지
4. 주관식 정답은 어떻게 할 것인지
