### ISSUE TITLE
Design UI/UX

### ISSUE THREAD

**Issue by jeonghyeonee** [jeonghyeonee/Memoriary#2]
Main Color: Green Color 
@hyunwestpark 
- [x] 일기쓰기
- [x] 퀴즈

@jeonghyeonee 
- [x] To-Do
- [x] Login + Join

@siheon0411 
- [x] 운동
- [x] My Page
- [x] Navigation Bar

Extra
- [ ] Push
- [ ] Image Detection

**Comment by jeonghyeonee** [comment]
[Memory UI/UX](https://www.figma.com/file/PnZeQaaiYTMNAVycB1uo3X/Memoriary?type=design&node-id=0%3A1&mode=design&t=FYKD8CrUKMVa5Csf-1)

**Comment by siheon0411** [comment]
https://www.figma.com/file/PnZeQaaiYTMNAVycB1uo3X/Memoriary?type=design&node-id=17-2&mode=design&t=wEkAaYC5dizvdZF7-0

현서가 만든 Navigation Bar 컨셉 디자인 너무 좋은데, 혹시 아이콘 이미지 밑에 글자도 추가해야하지 않을지?
