### ISSUE TITLE
Background, Concept of Application

### ISSUE THREAD

**Issue by jeonghyeonee** [jeonghyeonee/Memoriary#3]
Search the Background resources about our application

**Comment by jeonghyeonee** [comment]
- 치매앱이 왜 필요한가?
- 각 기능이 필요한 이유(e.g.: 운동 기능, Quiz, Reminder, ...)

**Comment by siheon0411** [comment]
### 근거자료

- [[서울시 치매예방프로그램](https://www.seouldementia.or.kr/common/e-book_2013/dementia_paper/pdf/paper_test1.pdf)](https://www.seouldementia.or.kr/common/e-book_2013/dementia_paper/pdf/paper_test1.pdf)
    
    치매에 운동이 좋다는 근거. 별다른 건질건 별로 없었음. 
    
- [[A systematic review of the application of a diary for people with dementia: how to maximise the effect of diary use?](https://onlinelibrary.wiley.com/doi/abs/10.1111/psyg.12800)](https://onlinelibrary.wiley.com/doi/abs/10.1111/psyg.12800)
    
    일기가 치매환자에 좋다는 논문. 일기를 주 기능으로 활용하는 근거로 사용.
    
- [[P2-439: Automatic analysis of hands clapping in severe Alzheimer patient via computer vision techniques](https://alz-journals.onlinelibrary.wiley.com/doi/full/10.1016/j.jalz.2011.05.1311)](https://alz-journals.onlinelibrary.wiley.com/doi/full/10.1016/j.jalz.2011.05.1311)
    
    박수를 컴퓨터비전으로 자동분석 한다는 논문. 이건 이번 proposal에서는 언급하지 말기로
    
- [[The applause sign in cortical and cortical-subcortical dementia](https://pubmed.ncbi.nlm.nih.gov/23212756/)](https://pubmed.ncbi.nlm.nih.gov/23212756/)
    
    박수로 치매 검증 및 박수가 좋다 1
    
- [[Applause sign in Alzheimer's disease: relationships to cognitive profile and severity of illness](https://pubmed.ncbi.nlm.nih.gov/23010943/)](https://pubmed.ncbi.nlm.nih.gov/23010943/)
    
    박수로 치매 검증 및 박수가 좋다 2
