### ISSUE TITLE
Implementation STT

### ISSUE THREAD

**Issue by jeonghyeonee** [jeonghyeonee/Memoriary#51]
We need to implement Text-to-Speech (TTS) and Speech-to-Text (STT) functionalities for enhancing the user experience in our diary and todo list features.

- Requirements:
  - **TTS Feature**:
      - Implement TTS to allow users to listen to their diary entries.  
      - Add a button/icon in the diary entry view to trigger TTS.  
      - Investigate and choose a suitable TTS library or API.  

  - **STT Feature**:
    - Implement STT for easy input in the diary and todo list.
    - Add a button/icon in the input fields to trigger STT.
    - Explore and select a reliable STT library or API.
    
   -  Additional Considerations:
      - Ensure compatibility with various languages.
      - Conduct thorough testing to ensure accuracy and reliability.

**Comment by siheon0411** [comment]
good
